export const SET_USER_DATA_REGISTER = "SET_USER_DATA_REGISTER";
export const SET_USER_DATA_CREATE_PROFILE = "SET_USER_DATA_CREATE_PROFILE";
export const CREATE_NEW_USER = "CREATE_NEW_USER";
export const GET_ALL_USERS = "GET_ALL_USERS";
